name: PR Validation

on:
  pull_request:
    branches: [ main, develop, 'task/*', 'bugfix/*', 'adhoc/*', 'feature/*' ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:
    name: Validate Code & Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate code
        run: ./gradlew validateCode

      - name: Run unit tests
        run: ./gradlew allTests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/build/test-results/
            **/build/reports/
          retention-days: 7